### ISSUE TITLE
Registrarse para Solicitar un Prestamo

### ISSUE THREAD

**Issue by gtovar** [gtovar/concapital#20]
Aqui es donde konconpital le pide al usuario que captura la siguiente informacion en 6 pasos:

- [ ] Primer paso       **Informacion del credito**
- [ ] Segundo paso   **Trabajo e Ingresos**
- [ ] Tercer paso       **Gastos Mensuales**
- [ ] Cuarto paso      **Referencias y datos bancarios**
- [ ] Quito paso        **Comprobantes**
- [ ] Sexto paso        **Enviar Solicitud**

 **Primero debe registrarse como usuario** #22
