### ISSUE TITLE
Ver pagina Principal

### ISSUE THREAD

**Issue by gtovar** [gtovar/concapital#25]
Todos los usuarios(solicitante e Inversionistas) que participaran en esta primera version podran ver el **Home**, esta pagina contendra 

- [x] Una barra de menus que representaran las secciones del sitio, ¿que secciones llevara?
- [x] Tendra como prestadero.com dos botones que seran los primeros y sobresaldran sobre todo el sitio al cargarse la pagina web. uno llevara a "quiero prestar #18 " y el otro a "quiero invertir #19"
- [x] **Registrarse** sera una seccion que definitivamente si tendra el **Home** aqui el usuario seleccionara de que manera **registrarse si como Solicitante** #20 y otra para registrarse como **quiero invertir** #23
- [x] LLevara un Simulador #24

**Comment by koncapital** [comment]
La barra de menú debe llevar "Quiero prestar" "quiero Invertir" "preguntas frecuentes" "acceso" "registrarse"

cuando das click en registrarte en cuando pueden aparecer las dos opciones "como solicitante" o "como inversionista"

**Comment by koncapital** [comment]
en la barra de menú consideramos mejor poner "como funciona" en lugar de "preguntas frecuentes.
